### ISSUE TITLE
ValueError: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by chinaheyu** [ros-visualization/rqt_graph#51]
$ rqt_console 
Traceback (most recent call last):
  File "/opt/ros/noetic/bin/rqt_console", line 8, in <module>
    sys.exit(main.main(sys.argv, standalone='rqt_console.console.Console'))
  File "/opt/ros/noetic/lib/python3/dist-packages/rqt_gui/main.py", line 61, in main
    return super(
  File "/opt/ros/noetic/lib/python3/dist-packages/qt_gui/main.py", line 407, in main
    from python_qt_binding import QT_BINDING
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/__init__.py", line 55, in <module>
    from .binding_helper import loadUi, QT_BINDING, QT_BINDING_MODULES, QT_BINDING_VERSION  # @UnusedImport
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 274, in <module>
    _select_qt_binding(
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 108, in _select_qt_binding
    QT_BINDING_VERSION = binding_loader(required_modules, optional_modules)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 155, in _load_pyqt
    _named_optional_import('PyQt5.%s' % module_name)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 142, in _named_optional_import
    _named_import(name)
  File "/opt/ros/noetic/lib/python3/dist-packages/python_qt_binding/binding_helper.py", line 133, in _named_import
    module = builtins.__import__(name)
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by dirk-thomas** [comment]
Please provide reproducible steps including information about the platform and how you installed / build ROS.

**Comment by 8krisv** [comment]
I have the same issue, did you solve it?

**Comment by tylernewnoise** [comment]
I run into the same iusse and could break it down to two installed PyQt5 packages - one was installed via apt and one via pip3. The probably had different versions, [this](https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe) gave be the wink in the right direction. By uninstalling PyQt5 and PyQt5-sip with pip3 the problem didn't occur anymore. Maybe this helps.

**Comment by 8krisv** [comment]
¡thanks, that solved my problem!
