### ISSUE TITLE
ROS Melodic on Ubuntu 18.04 Crashing When Trying To Select Nodes Only

### ISSUE THREAD

**Issue by cwillia109** [ros-visualization/rqt_graph#52]
When trying to view nodes only, the command crashes and reports all of the below:

```
['dot', '-Tdot', '/tmp/tmpm8fcMf'] return code: 1

stdout, stderr:
 digraph graphname {
	graph [bb="0,0,949.15,2257",
		compound=True,
		rank=same,
		rankdir=LR,
		ranksep=0.2
	];
	node [label="\N"];
	subgraph cluster___tb3_2 {
		graph [bb="8,596.03,941.15,704.03",
			compound=True,
			label="/tb3_2",
			lheight=0.21,
			lp="474.57,692.53",
			lwidth=0.49,
			rank=same,
			rankdir=LR,
			ranksep=0.2,
			style=bold
		];
		n___tb3_2__move_base		 [URL=__tb3_2__move_base,
			height=0.5,
			label="/tb3_2/move_base",
			pos="857.75,622.03",
			shape=ellipse,
			tooltip="/tb3_2/move_base",
			width=2.0943];
		n___tb3_2__move_base -> n___tb3_2__move_base		 [URL=topic_3A__tb3_2__move_base__goal,
			label="/tb3_2/move_base/goal",
			lp="857.75,665.53",
			penwidth=1,
			pos="e,872.49,639.81 843.01,639.81 840.51,649.35 845.42,658.03 857.75,658.03 865.27,658.03 870.03,654.81 872.03,650.13"];
		n___tb3_2__amcl		 [URL=__tb3_2__amcl,
			height=0.5,
			label="/tb3_2/amcl",
			pos="597.07,777.03",
			shape=ellipse,
			tooltip="/tb3_2/amcl",
			width=1.4804];
		n___tb3_2__amcl -> n___tb3_2__move_base		 [URL=topic_3A__tf,
			label="/tf",
			lp="758.86,692.53",
			penwidth=1,
			pos="e,829.28,638.96 623.5,761.32 670.12,733.6 767.07,675.95 820.47,644.2"];
		n___tb3_2__amcl -> n___tb3_2__amcl		 [URL=topic_3A__tf,
			label="/tf",
			lp="597.07,820.53",
			penwidth=1,
			pos="e,613.49,794.44 580.64,794.44 577.58,804.12 583.05,813.03 597.07,813.03 605.83,813.03 611.25,809.55 613.34,804.58"];
		n___tb3_2__robot_state_publisher		 [URL=__tb3_2__robot_state_publisher,
			height=0.5,
			label="/tb3_2/robot_state_publisher",
			pos="127.79,642.03",
			shape=ellipse,
			tooltip="/tb3_2/robot_state_publisher",
			width=3.1053];
		n___tb3_2__robot_state_publisher -> n___tb3_2__move_base	 [URL=topic_3A__tf,
			label="/tf",
			lp="597.07,615.53",
			penwidth=1,
			pos="e,786.98,615.59 187.12,626.76 206.28,622.47 227.71,618.35 247.58,616.03 436.03,594.05 659.44,605.76 776.66,614.78"];
		n___tb3_2__robot_state_publisher -> n___tb3_2__amcl		 [URL=topic_3A__tf,
			label="/tf",
			lp="410.18,628.53",
			penwidth=1,
			pos="e,595.14,758.68 214.24,630.55 318.08,618.6 484.7,605.83 535.77,639.03 573.06,663.27 587.84,715.98 593.58,748.79"];
	}
	subgraph cluster___tb3_1 {
		graph [bb="8,222.03,941.15,381.03",
			compound=True,
			label="/tb3_1",
			lheight=0.21,
			lp="474.57,369.53",
			lwidth=0.49,
			rank=same,
			rankdir=LR,
			ranksep=0.2,
			style=bold
		];
		n___tb3_1__amcl		 [URL=__tb3_1__amcl,
			height=0.5,
			label="/tb3_1/amcl",
			pos="597.07,299.03",
			shape=ellipse,
			tooltip="/tb3_1/amcl",
			width=1.4804];
		n___tb3_1__amcl -> n___tb3_1__amcl		 [URL=topic_3A__tf,
			label="/tf",
			lp="597.07,342.53",
			penwidth=1,
			pos="e,613.49,316.44 580.64,316.44 577.58,326.12 583.05,335.03 597.07,335.03 605.83,335.03 611.25,331.55 613.34,326.58"];
		n___tb3_1__move_base		 [URL=__tb3_1__move_base,
			height=0.5,
			label="/tb3_1/move_base",
			pos="857.75,268.03",
			shape=ellipse,
			tooltip="/tb3_1/move_base",
			width=2.0943];
		n___tb3_1__amcl -> n___tb3_1__move_base		 [URL=topic_3A__tf,
			label="/tf",
			lp="758.86,288.53",
			penwidth=1,
			pos="e,790.06,276.08 647.64,293.02 685.2,288.55 737.11,282.38 779.94,277.28"];
		n___tb3_1__move_base -> n___tb3_1__move_base		 [URL=topic_3A__tb3_1__move_base__goal,
			label="/tb3_1/move_base/goal",
			lp="857.75,311.53",
			penwidth=1,
			pos="e,872.49,285.81 843.01,285.81 840.51,295.35 845.42,304.03 857.75,304.03 865.27,304.03 870.03,300.81 872.03,296.13"];
		n___tb3_1__robot_state_publisher		 [URL=__tb3_1__robot_state_publisher,
			height=0.5,
			label="/tb3_1/robot_state_publisher",
			pos="127.79,259.03",
			shape=ellipse,
			tooltip="/tb3_1/robot_state_publisher",
			width=3.1053];
		n___tb3_1__robot_state_publisher -> n___tb3_1__amcl		 [URL=topic_3A__tf,
			label="/tf",
			lp="410.18,274.53",
			penwidth=1,
			pos="e,555.09,287.75 222.87,249.5 231.22,248.91 239.55,248.4 247.58,248.03 291.98,246 303.36,243.56 347.58,248.03 416.71,255.02 495,272.65 \
545.14,285.22"];
		n___tb3_1__robot_state_publisher -> n___tb3_1__move_base	 [URL=topic_3A__tf,
			label="/tf",
			lp="597.07,255.53",
			penwidth=1,
			pos="e,789.97,260.15 206.56,246.24 220.2,244.49 234.27,242.97 247.58,242.03 438.54,228.55 663.65,247.02 779.75,259.07"];
	}
	subgraph cluster___tb3_0 {
		graph [bb="8,2056,941.15,1412",
			compound=True,
			label="/tb3_0",
			lheight=0.21,
			lp="474.57,1400.5",
			lwidth=0.49,
			rank=same,
			rankdir=LR,
			ranksep=0.2,
			style=bold
		];
		n___tb3_0__move_base		 [URL=__tb3_0__move_base,
			height=0.5,
			label="/tb3_0/move_base",
			pos="857.75,1739",
			shape=ellipse,
			tooltip="/tb3_0/move_base",
			width=2.0943];
		n___tb3_0__move_base -> n___tb3_0__move_base		 [URL=topic_3A__tb3_0__move_base__goal,
			label="/tb3_0/move_base/goal",
			lp="857.75,1782.5",
			penwidth=1,
			pos="e,872.49,1756.8 843.01,1756.8 840.51,1766.3 845.42,1775 857.75,1775 865.27,1775 870.03,1771.8 872.03,1767.1"];
		n___tb3_0__robot_state_publisher		 [URL=__tb3_0__robot_state_publisher,
			height=0.5,
			label="/tb3_0/robot_state_publisher",
			pos="127.79,1384",
			shape=ellipse,
			tooltip="/tb3_0/robot_state_publisher",
			width=3.1053];
		n___tb3_0__robot_state_publisher -> n___tb3_0__move_base	 [URL=topic_3A__tf,
			label="/tf",
			lp="597.07,2196.5",
			penwidth=1,
			pos="e,855.84,1757.2 218.87,1394.6 226.77,1398.7 233.91,1404.1 239.58,1411 248.07,1421.5 244.05,1640.1 247.58,1653 272,1742.8 322.61,\
1747.4 347.58,1837 352.83,1855.9 346.06,1995.9 355.58,2013 404.88,2101.6 450.85,2101.4 543.77,2142 626.14,2178 673.13,2222.9 744.36,\
2168 809.33,2118 844.66,1854.5 854.72,1767.2"];
		n___tb3_0__amcl		 [URL=__tb3_0__amcl,
			height=0.5,
			label="/tb3_0/amcl",
			pos="597.07,2082",
			shape=ellipse,
			tooltip="/tb3_0/amcl",
			width=1.4804];
		n___tb3_0__robot_state_publisher -> n___tb3_0__amcl		 [URL=topic_3A__tf,
			label="/tf",
			lp="410.18,2001.5",
			penwidth=1,
			pos="e,568.83,2066.6 217.31,1394.9 225.67,1398.9 233.33,1404.2 239.58,1411 248.04,1420.3 245.02,1454.7 247.58,1467 281.7,1630.9 310.35,\
1666.9 347.58,1830 352,1849.4 345.71,1856.8 355.58,1874 405.33,1961 505.48,2029 559.86,2061.3"];
		n___tb3_0__amcl -> n___tb3_0__move_base		 [URL=topic_3A__tf,
			label="/tf",
			lp="758.86,1367.5",
			penwidth=1,
			pos="e,855.83,1720.8 606.15,2100.1 616.19,2117.8 634.21,2143.8 658.36,2155 693,2171.2 717.2,2181.9 744.36,2155 760.06,2139.5 736.67,1375.6 \
752.36,1360 804.82,1308.1 843.83,1614.1 854.7,1710.6"];
		n___tb3_0__amcl -> n___tb3_0__amcl		 [URL=topic_3A__tf,
			label="/tf",
			lp="597.07,2125.5",
			penwidth=1,
			pos="e,613.49,2099.4 580.64,2099.4 577.58,2109.1 583.05,2118 597.07,2118 605.83,2118 611.25,2114.6 613.34,2109.6"];
	}
	n___gazebo	 [URL=__gazebo,
		height=0.5,
		label="/gazebo",
		pos="410.18,1007",
		shape=ellipse,
		tooltip="/gazebo",
		width=1.0652];
	n___tb3_2__move_base -> n___gazebo	 [URL=topic_3A__tb3_2__cmd_vel,
		label="/tb3_2/cmd_vel",
		lp="701.36,1014.5",
		penwidth=1,
		pos="e,448.44,1009.2 855.16,640.19 844.99,708.35 805.39,946.94 744.36,986.03 698.39,1015.5 540,1013 458.88,1009.6"];
	n___tb3_2__amcl -> n___tb3_1__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="504.27,734.03",
		penwidth=1,
		pos="e,592.17,317.18 550.65,768.13 536.04,762.9 521.47,754.63 512.77,741.53 509.08,735.98 512.12,733.17 512.77,726.53 527.67,573.95 571.81,\
395.04 589.55,327.1"];
	n___tb3_2__amcl -> n___tb3_1__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="758.86,433.53",
		penwidth=1,
		pos="e,849.95,286.11 606.28,759.15 618.89,733.69 640.99,685.19 650.36,641.03 654.49,621.56 646.47,478 658.36,462.03 682.53,429.56 712.15,\
456.55 744.36,432.03 792.7,395.23 828.05,331.81 845.51,295.57"];
	n___tb3_2__amcl -> n___tb3_0__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="758.86,910.53",
		penwidth=1,
		pos="e,856.32,1720.8 633.18,790.44 675.41,808.49 742.46,845.17 765.36,903.03 795.73,979.79 844.54,1573.2 855.51,1710.7"];
	n___tb3_2__amcl -> n___tb3_0__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="504.27,944.03",
		penwidth=1,
		pos="e,595.19,2063.8 584.1,794.51 564.12,822.67 526.64,880.6 512.77,936.53 511.17,943 512.52,944.87 512.77,951.53 529.15,1391.6 581.28,\
1925.9 594.17,2053.6"];
	n___tb3_2__robot_state_publisher -> n___tb3_1__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="410.18,327.53",
		penwidth=1,
		pos="e,543.79,301.07 136.57,623.96 156.54,582.42 206.2,476.7 239.58,385.03 243.86,373.27 238.39,366.53 247.58,358.03 288.25,320.42 444.61,\
306.53 533.79,301.6"];
	n___tb3_2__robot_state_publisher -> n___tb3_1__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="597.07,115.53",
		penwidth=1,
		pos="e,855.27,249.99 137.98,624.04 160.64,583.1 215.09,479.21 239.58,385.03 248.68,350.02 233.64,337.41 247.58,304.03 291.18,199.58 296.99,\
108.03 410.18,108.03 410.18,108.03 410.18,108.03 758.86,108.03 820.21,108.03 844.77,194.2 853.5,240.06"];
	n___tb3_2__robot_state_publisher -> n___tb3_0__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="597.07,1180.5",
		penwidth=1,
		pos="e,856.16,1721 139.42,660.05 177.01,719.31 295.82,914.62 347.58,1094 352.1,1109.7 343.52,1156 355.58,1167 422.88,1228.4 696.46,1114.5 \
765.36,1174 806.7,1209.8 845.21,1601.2 855.23,1710.7"];
	n___tb3_2__robot_state_publisher -> n___tb3_0__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="410.18,1754.5",
		penwidth=1,
		pos="e,589.98,2064.1 130.04,660.4 139.4,734.13 177.94,1015.4 247.58,1237 280.99,1343.4 304.4,1364.3 347.58,1467 442.57,1693.1 552.05,\
1968.3 586.28,2054.7"];
	n___tb3_1__amcl -> n___tb3_2__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="758.86,378.53",
		penwidth=1,
		pos="e,855.98,604 643.22,308.16 680.74,317.81 732.64,336.58 765.36,371.03 826.41,435.31 847.79,543.32 854.71,594.08"];
	n___tb3_1__amcl -> n___tb3_2__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="504.27,714.03",
		penwidth=1,
		pos="e,561.6,763.45 591.95,317.1 576.16,373.85 528.4,553.81 512.77,706.53 512.09,713.16 509.61,715.66 512.77,721.53 521.46,737.65 537.1,\
749.86 552.56,758.66"];
	n___tb3_1__amcl -> n___tb3_0__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="758.86,584.53",
		penwidth=1,
		pos="e,856.56,1720.9 616.91,315.85 628.63,325.45 643.95,337.45 658.36,347.03 694.81,371.26 720.07,358.62 744.36,395.03 750.01,403.5 764.37,\
566.9 765.36,577.03 809.36,1028.6 847.16,1580.5 855.87,1710.6"];
	n___tb3_1__amcl -> n___tb3_0__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="504.27,924.03",
		penwidth=1,
		pos="e,594.12,2063.9 593.22,317.12 583.61,362.92 558.27,487.3 543.77,592.03 523.9,735.54 519.67,771.82 512.77,916.53 491.1,1371.3 572.22,\
1924.5 592.55,2054"];
	n___tb3_1__move_base -> n___gazebo	 [URL=topic_3A__tb3_1__cmd_vel,
		label="/tb3_1/cmd_vel",
		lp="701.36,552.53",
		penwidth=1,
		pos="e,414.91,988.85 850.77,286.01 837.31,319.36 805.54,392.19 765.36,445.03 725.96,496.84 685.74,485.98 658.36,545.03 643.11,577.93 \
663.75,674.33 650.36,708.03 621.42,780.85 596.75,792.81 535.77,842.03 511.01,862.02 494.71,852.99 472.77,876.03 444.6,905.62 427.01,\
950.26 417.89,979.03"];
	n___tb3_1__robot_state_publisher -> n___tb3_2__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="597.07,78.531",
		penwidth=1,
		pos="e,852.39,603.66 134.81,240.86 149.56,205.43 187.5,127.65 247.58,94.031 404.05,6.4727 520.17,-52.264 650.36,71.031 662.24,82.279 \
651.9,203 658.36,218.03 680.33,269.16 713.28,262.88 744.36,309.03 777.15,357.72 829.3,526.21 849.44,593.73"];
	n___tb3_1__robot_state_publisher -> n___tb3_2__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="410.18,558.53",
		penwidth=1,
		pos="e,589.77,759.08 236.82,254.95 277.49,259.44 320.36,272.47 347.58,304.03 358.19,316.33 348.7,435.32 355.58,450.03 401.98,549.21 475.99,\
526.3 535.77,618.03 541.68,627.1 540.02,630.88 543.77,641.03 557.79,678.95 575.02,722.38 586.02,749.76"];
	n___tb3_1__robot_state_publisher -> n___tb3_0__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="597.07,1143.5",
		penwidth=1,
		pos="e,856.73,1720.9 135.61,277 156.63,326.26 214.49,468 239.58,592.03 248.95,638.34 232.26,653.34 247.58,698.03 273.67,774.18 322.71,\
772.48 347.58,849.03 353.94,868.6 345.44,1016.1 355.58,1034 384.24,1084.6 421.82,1066.9 464.77,1106 468.98,1109.9 467.81,1113.2 \
472.77,1116 592.36,1183.3 736.87,1050 774.36,1182 830.48,1379.6 850.65,1628 856.08,1710.8"];
	n___tb3_1__robot_state_publisher -> n___tb3_0__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="410.18,1482.5",
		penwidth=1,
		pos="e,593.81,2064 142.36,277.19 184.2,330.65 304.51,493.61 347.58,652.03 358.72,693 350,991.95 355.58,1034 382.12,1234.2 416.88,1278.9 \
464.77,1475 496.75,1606 506.99,1638.3 535.77,1770 558.58,1874.4 581.94,1999.4 591.98,2054.1"];
	n___tb3_0__move_base -> n___gazebo	 [URL=topic_3A__tb3_0__cmd_vel,
		label="/tb3_0/cmd_vel",
		lp="701.36,1061.5",
		penwidth=1,
		pos="e,441.76,1017.3 856.39,1721 849.34,1630.3 815.91,1223.2 774.36,1104 765.83,1079.6 766.2,1068 744.36,1054 693.21,1021.4 532.34,1036.7 \
472.77,1025 465.91,1023.7 458.71,1021.9 451.74,1020.1"];
	n___tb3_0__robot_state_publisher -> n___tb3_2__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="597.07,2249.5",
		penwidth=1,
		pos="e,855.56,640.12 218.94,1394.6 226.83,1398.7 233.94,1404 239.58,1411 251.41,1425.7 244.27,1731.5 247.58,1750 273.63,1896.1 268.52,\
1945.8 355.58,2066 440.89,2183.8 541,2303.9 650.36,2208 770.21,2103 729.58,1655.7 744.36,1497 750.43,1431.9 744.05,1414.9 752.36,\
1350 756.05,1321.2 759.95,1314.5 765.36,1286 769.65,1263.4 770.81,1257.8 774.36,1235 809.49,1010.1 843.61,737.47 854.31,650.27"];
	n___tb3_0__robot_state_publisher -> n___tb3_2__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="410.18,773.53",
		penwidth=1,
		pos="e,593.04,758.97 129.59,1366 140.13,1271.3 203.08,829.7 472.77,667.03 496.75,652.57 511.63,652.85 535.77,667.03 565.72,684.63 582.11,\
722.76 590.23,749.16"];
	n___tb3_0__robot_state_publisher -> n___tb3_1__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="410.18,388.53",
		penwidth=1,
		pos="e,557.92,311.38 130.92,1366 144.46,1287.9 199.23,969.91 239.58,708.03 243.41,683.18 241.1,676.32 247.58,652.03 280.98,526.75 261.55,\
470.3 355.58,381.03 362.82,374.16 479.75,336.26 548.2,314.47"];
	n___tb3_0__robot_state_publisher -> n___tb3_1__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="597.07,185.53",
		penwidth=1,
		pos="e,836.65,250.41 131.75,1365.9 148.61,1287.6 214.64,971.53 239.58,708.03 241.27,690.22 238.16,401.25 247.58,386.03 274.05,343.26 \
319.7,374.9 347.58,333.03 358.34,316.87 343.71,261.39 355.58,246.03 409.96,175.66 456.17,193.37 543.77,178.03 631.86,162.6 661.09,\
161.41 744.36,194.03 775.28,206.14 806.6,227.42 828.46,244.06"];
	n___tb3_0__amcl -> n___tb3_2__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="758.86,1278.5",
		penwidth=1,
		pos="e,856.99,640.25 599.04,2064 609.02,1975.7 657.17,1580.7 752.36,1271 759.61,1247.4 767.71,1243.8 774.36,1220 834.17,1006.3 852.09,\
737.14 856.5,650.36"];
	n___tb3_0__amcl -> n___tb3_2__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="504.27,904.03",
		penwidth=1,
		pos="e,579.7,794.12 595.26,2063.8 584.59,1955.2 529.67,1381.4 512.77,911.53 512.53,904.87 510.75,902.89 512.77,896.53 524.51,859.51 552.32,\
824.07 572.8,801.53"];
	n___tb3_0__amcl -> n___tb3_1__amcl	 [URL=topic_3A__tf,
		label="/tf",
		lp="504.27,964.03",
		penwidth=1,
		pos="e,593.16,317.11 594.1,2063.8 577.11,1957.7 493.64,1407.3 512.77,956.53 519.67,794.09 522.31,753.19 543.77,592.03 556.83,493.98 580.13,\
378.84 591.08,326.91"];
	n___tb3_0__amcl -> n___tb3_1__move_base	 [URL=topic_3A__tf,
		label="/tf",
		lp="758.86,1115.5",
		penwidth=1,
		pos="e,852.36,286.09 597.49,2063.8 600.05,1961 614.75,1451.9 658.36,1302 681.14,1223.8 720.89,1218.1 744.36,1140 772.38,1046.8 758.19,\
1019.1 765.36,922.03 776.18,775.57 761.86,737.45 782.36,592.03 798.04,480.82 833.4,351.61 849.5,295.91"];
	n___map_server	 [URL=__map_server,
		height=0.5,
		label="/map_server",
		pos="410.18,423.03",
		shape=ellipse,
		tooltip="/map_server",
		width=1.5165];
	n___map_server -> n___tb3_2__move_base	 [URL=topic_3A__map,
		label="/map",
		lp="701.36,413.53",
		penwidth=1,
		pos="e,856.09,603.98 459.37,415.13 544.83,402.47 716.29,382.14 765.36,414.03 827.45,454.39 848.15,547.12 854.78,593.92"];
	n___map_server -> n___tb3_2__amcl	 [URL=topic_3A__map,
		label="/map",
		lp="504.27,455.53",
		penwidth=1,
		pos="e,587.83,759.15 463.65,427.14 493.39,430.63 526.27,436.93 535.77,448.03 549.73,464.34 539.35,620.03 543.77,641.03 552.05,680.37 \
570.51,723.14 583.37,750.01"];
	n___map_server -> n___tb3_1__amcl	 [URL=topic_3A__map,
		label="/map",
		lp="504.27,392.53",
		penwidth=1,
		pos="e,583.67,316.65 434.53,406.72 445.87,399.53 459.71,391.31 472.77,385.03 499.64,372.12 510.75,378.23 535.77,362.03 551.32,351.96 \
565.91,337.27 576.95,324.61"];
	n___map_server -> n___tb3_1__move_base	 [URL=topic_3A__map,
		label="/map",
		lp="701.36,226.53",
		penwidth=1,
		pos="e,831.94,251.06 439.61,407.77 448.79,401.77 458.21,394.11 464.77,385.03 472.1,374.88 468,369.6 472.77,358.03 498.14,296.44 486.59,\
260.2 543.77,226.03 631.74,173.46 674.65,202.34 774.36,226.03 791.18,230.03 808.46,237.98 822.89,245.9"];
	n___map_server -> n___tb3_0__move_base	 [URL=topic_3A__map,
		label="/map",
		lp="701.36,936.53",
		penwidth=1,
		pos="e,857.42,1720.9 450.26,435.26 455.61,438.16 460.66,441.71 464.77,446.03 465.77,447.08 535.43,640.62 535.77,642.03 542.62,670.77 \
533.52,680.32 543.77,708.03 575.63,794.19 591.18,817.39 658.36,880.03 690.53,910.03 718.99,893.1 744.36,929.03 836.18,1059.1 854.15,\
1582.7 857.19,1710.7"];
	n___map_server -> n___tb3_0__amcl	 [URL=topic_3A__map,
		label="/map",
		lp="504.27,1107.5",
		penwidth=1,
		pos="e,595.99,2064 445.83,436.84 453.35,441.47 460.34,447.44 464.77,455.03 479.33,479.99 465.87,946.97 472.77,975.03 487.63,1035.4 519.5,\
1040 535.77,1100 538.98,1111.9 585.79,1893.3 595.36,2053.5"];
	n___gazebo_gui	 [URL=__gazebo_gui,
		height=0.5,
		label="/gazebo_gui",
		pos="127.79,1438",
		shape=ellipse,
		tooltip="/gazebo_gui",
		width=1.4985];
	n___gazebo -> n___tb3_2__move_base	 [URL=topic_3A__tb3_2__scan,
		label="/tb3_2/scan",
		lp="701.36,976.53",
		penwidth=1,
		pos="e,854.56,640.12 447.2,1002 528.82,990.66 718.96,963.02 744.36,948.03 797.73,916.54 838.88,723.14 852.72,650.01"];
	n___gazebo -> n___tb3_2__amcl	 [URL=topic_3A__tb3_2__scan,
		label="/tb3_2/scan",
		lp="504.27,834.53",
		penwidth=1,
		pos="e,550.33,785.87 411.59,988.92 415.3,953.31 428.37,873.61 472.77,827.03 490.83,808.09 517.02,796.14 540.7,788.7"];
	n___gazebo -> n___tb3_2__robot_state_publisher	 [URL=topic_3A__tb3_2__joint_states,
		label="/tb3_2/joint_states",
		lp="297.58,715.53",
		penwidth=1,
		pos="e,228.69,649.82 406.6,988.7 394.04,924.48 352.44,713.33 347.58,708.03 319.57,677.53 278.08,660.91 238.66,651.94"];
	n___gazebo -> n___tb3_1__amcl	 [URL=topic_3A__tb3_1__scan,
		label="/tb3_1/scan",
		lp="504.27,694.53",
		penwidth=1,
		pos="e,590.3,316.95 414.02,988.93 423.25,945.32 447.15,830.96 464.77,735.03 468.68,713.76 467.68,708.05 472.77,687.03 506.12,549.3 563.4,\
389.51 586.73,326.54"];
	n___gazebo -> n___tb3_1__move_base	 [URL=topic_3A__tb3_1__scan,
		label="/tb3_1/scan",
		lp="701.36,868.53",
		penwidth=1,
		pos="e,852.57,286.16 414.83,988.84 422.38,963.34 439.87,917.56 472.77,895.03 538.53,849.99 589.66,921.68 650.36,870.03 766.95,770.82 \
690.96,681.27 752.36,541.03 760.19,523.15 766.17,520.75 774.36,503.03 807.82,430.63 836.31,340.73 849.66,296.01"];
	n___gazebo -> n___tb3_1__robot_state_publisher	 [URL=topic_3A__tb3_1__joint_states,
		label="/tb3_1/joint_states",
		lp="297.58,403.53",
		penwidth=1,
		pos="e,179.84,275.11 405.43,989.06 394.25,945.74 366.37,831.97 355.58,735.03 353.5,716.31 356.92,412.39 347.58,396.03 313.49,336.29 241.66,\
299.02 189.36,278.71"];
	n___gazebo -> n___tb3_0__move_base	 [URL=topic_3A__tb3_0__odom,
		label="/tb3_0/odom",
		lp="701.36,1095.5",
		penwidth=1,
		pos="e,856.46,1720.8 427.39,1023.2 439.25,1033.4 455.86,1045.9 472.77,1053 535.59,1079.4 731.77,1054.9 774.36,1108 812.63,1155.8 847.13,\
1593.7 855.72,1710.5"];
	n___gazebo -> n___tb3_0__robot_state_publisher	 [URL=topic_3A__tb3_0__joint_states,
		label="/tb3_0/joint_states",
		lp="297.58,1225.5",
		penwidth=1,
		pos="e,141.41,1365.8 397.34,1024.2 352.39,1084.2 201.86,1285.1 147.54,1357.7"];
	n___gazebo -> n___tb3_0__amcl	 [URL=topic_3A__tb3_0__scan,
		label="/tb3_0/scan",
		lp="504.27,1222.5",
		penwidth=1,
		pos="e,596.34,2063.9 419.55,1024.7 431.48,1047 452.9,1086.3 472.77,1119 499.24,1162.7 519.44,1166.7 535.77,1215 563.12,1296 590.08,1913 \
595.91,2053.6"];
}

Error: trouble in init_rank
	%0 2
	%0 10
	%0 7
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	n___tb3_0__move_base 2
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	n___tb3_0__amcl 6
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	%0 2
	%0 1
	n___tb3_0__robot_state_publisher 2
	n___tb3_2__amcl 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	n___gazebo 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	n___gazebo_gui 2


Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 289, in _refresh_rosgraph
    self._update_graph_view(self._generate_dotcode())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/ros_graph.py", line 324, in _generate_dotcode
    hide_dynamic_reconfigure=hide_dynamic_reconfigure)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rqt_graph/dotcode.py", line 914, in generate_dotcode
    dotcode = dotcode_factory.create_dot(dotgraph)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/qt_dotgraph/pydotfactory.py", line 175, in create_dot
    dot = graph.create_dot()
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 1681, in <lambda>
    self.create(format=f, prog=prog))
  File "/usr/lib/python2.7/dist-packages/pydot.py", line 1900, in create
    assert p.returncode == 0, p.returncode
AssertionError: 1
```

**Comment by dirk-thomas** [comment]
Please provide reproducible steps.

**Comment by Jayadev22** [comment]
I'm facing the same problem. Is there a solution to this.?
Thank you.

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as May 31st 2025, so I'm closing this.

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
